sudo: false
language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - 7
before_script:
  - composer self-update
  - composer install
  - openssl genrsa -out private.key 1024
  - openssl rsa -in private.key -pubout -out public.key
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover